version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
# python:
#   version: 3.8
#   install:
#     - requirements: docs/requirements.txt

sphinx:
   configuration: docs/conf.py
